services:
  db:
    image: postgres:16.8-alpine3.20
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5433:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      retries: 5
      start_period: 10s

  migrate:
    image: migrate/migrate
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./pkg/migrations:/migrations
    entrypoint: ["/bin/sh", "-c"]
    command: >
      "migrate -path=/migrations -database=postgres://${DB_USER}:${DB_PASSWORD}@db:5432/${DB_NAME}?sslmode=disable up"
  redis:
    image: redis:8.0-rc1-alpine
    ports:
      - "6379:6379"                                
    restart: always                              
    volumes:
      - redis-data:/data                          
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      retries: 5
      start_period: 10s

volumes:
  db-data:
  redis-data: